language: go

go:
  - master
  - "1.10"

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  - pushd examples/chatroom/client && go build
  - pushd ../server && go build
  - popd && popd

  - pushd examples/echo/client && go build
  - pushd ../server && go build
  - popd && popd

  - pushd examples/pubsub/client && go build
  - pushd ../server && go build
  - popd && popd

  # Run all the tests with the race detector enabled
  - overalls -project=github.com/qbeon/webwire-go -covermode=atomic -debug -- -race -v -coverpkg=./...
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN

  # go vet is the official Go static analyzer
  - go vet ./...

  # "go vet on steroids" + linter
  - megacheck ./...

  # forbid code with huge functions
  - gocyclo -over 20 $GO_FILES

  # one last linter
  - golint -set_exit_status $(go list ./...)
